default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: brighton0102
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hellorails_development

test:
  <<: *default
  database: hellorails_test

production:
  database: hellorails_production
  <<: *default